services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: unless-stopped
    ports:
      - "${API_PORT:-4000}:4000"
    env_file:
      - apps/api/.env
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - tdd-workshop
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - tdd-workshop
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  tdd-workshop:
    name: tdd-workshop 